" --- Confiture UI ---
set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to
set showmatch           " highlight matching [{()}]

" --- Configure Search ---
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" --- Configure Folding ---
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level

" --- Configure Leader ---
let mapleader=","       " leader is comma
"     --- Edit vimrc/zshrc and load vimrc bindings
nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>ez :vsp ~/.zshrc<CR>
nnoremap <leader>eb :vsp ~/.bashrc<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>
"     --- Save session
nnoremap <leader>s :mksession<CR>

" --- Configure TMux ---
"     --- allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" --- Configure Color Scheme --- 
colorscheme badwolf

" --- Configure Tabs ---
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

" --- Configure IDE ---
syntax enable

